//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Aashish Adhikari @asisadh
//  http://aashishadhikari.com.np
//

import Foundation

struct ___VARIABLE_MODULENAME___ResponseModel{
    
}
