//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Aashish Adhikari @asisadh
//  http://aashishadhikari.com.np
//

import Foundation
import UIKit

class ___VARIABLE_MODULENAME___WireFrame: ___VARIABLE_MODULENAME___WireFrameProtocol {
    static func create___VARIABLE_MODULENAME___Model() -> UIViewController{
        
        #error("Change the view controller as needed")
        let viewController = UIViewController()
        if let view = viewController as? ___VARIABLE_MODULENAME___ {
            let presenter: ___VARIABLE_MODULENAME___PresenterProtocol & ___VARIABLE_MODULENAME___InteractorOutputProtocol = ___VARIABLE_MODULENAME___Presenter()
            let interactor: ___VARIABLE_MODULENAME___InteractorInputProtocol & ___VARIABLE_MODULENAME___DataManagerOutPutProtocol = ___VARIABLE_MODULENAME___Interactor()
            let remoteDataManager: ___VARIABLE_MODULENAME___DataManagerInputProtocol = ___VARIABLE_MODULENAME___RemoteDataManager()
            let wireFrame: ___VARIABLE_MODULENAME___WireFrameProtocol = ___VARIABLE_MODULENAME___WireFrame()
            
            view.presenter = presenter
            
            presenter.view = view
            presenter.interactor = interactor
            presenter.wireFrame = wireFrame
            
            interactor.presenter = presenter
            interactor.remoteDataManager = remoteDataManager
            
            remoteDataManager.remoteRequestHandler = interactor
            
            return viewController
        }
        
        return UIViewController()
    }
}
