//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Aashish Adhikari @asisadh
//  http://aashishadhikari.com.np
//

import UIKit

class ___VARIABLE_MODULENAME___: UIViewController {
    var presenter: ___VARIABLE_MODULENAME___PresenterProtocol?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.viewDidLoad()
    }
}

extension ___VARIABLE_MODULENAME___: ___VARIABLE_MODULENAME___Protocol {
    func showError(message: String){
        
    }
    
    func showLoading(){
        
    }
    
    func hideLoading(){
        
    }
}
