//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Aashish Adhikari @asisadh
//  http://aashishadhikari.com.np
//

import UIKit

class ___VARIABLE_MODULENAME___Presenter: ___VARIABLE_MODULENAME___PresenterProtocol {
    var view: ___VARIABLE_MODULENAME___Protocol?
    var interactor: ___VARIABLE_MODULENAME___InteractorInputProtocol?
    var wireFrame: ___VARIABLE_MODULENAME___WireFrameProtocol?
    
    func viewDidLoad(){
        view?.showLoading()
    }
}

extension ___VARIABLE_MODULENAME___Presenter: ___VARIABLE_MODULENAME___InteractorOutputProtocol{
    func onError(message: String){
        view?.hideLoading()
        view?.showError(message: message)
    }
}
