//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Aashish Adhikari @asisadh
//  http://aashishadhikari.com.np
//

import Foundation

class ___VARIABLE_MODULENAME___Interactor:___VARIABLE_MODULENAME___InteractorInputProtocol {
    var presenter: ___VARIABLE_MODULENAME___InteractorOutputProtocol?
    var remoteDataManager: ___VARIABLE_MODULENAME___DataManagerInputProtocol?
}

extension  ___VARIABLE_MODULENAME___Interactor: ___VARIABLE_MODULENAME___DataManagerOutPutProtocol{
   
    func onError(message: String) {
        presenter?.onError(message: message)
    }
}
